// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV1uQ4ZQXTEJsz2vIlMn_djQc-KQ0LcHA',
    appId: '1:769071272569:web:5f5aabc6b0c8d345dcfaa8',
    messagingSenderId: '769071272569',
    projectId: 'app-conect-biblioteca',
    authDomain: 'app-conect-biblioteca.firebaseapp.com',
    storageBucket: 'app-conect-biblioteca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvBAw7EXwxLtUsjobTqf2ISa7A-vjPutE',
    appId: '1:769071272569:android:00055b34a3ed189fdcfaa8',
    messagingSenderId: '769071272569',
    projectId: 'app-conect-biblioteca',
    storageBucket: 'app-conect-biblioteca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEOPwU1vTyPg15tlUk-u-yvv-O1auBjcE',
    appId: '1:769071272569:ios:a931a7ad386be923dcfaa8',
    messagingSenderId: '769071272569',
    projectId: 'app-conect-biblioteca',
    storageBucket: 'app-conect-biblioteca.appspot.com',
    iosClientId: '769071272569-l712oqbup15vaia0j4qkcavvk6m5il6o.apps.googleusercontent.com',
    iosBundleId: 'com.example.appConectBiblioteca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEOPwU1vTyPg15tlUk-u-yvv-O1auBjcE',
    appId: '1:769071272569:ios:a931a7ad386be923dcfaa8',
    messagingSenderId: '769071272569',
    projectId: 'app-conect-biblioteca',
    storageBucket: 'app-conect-biblioteca.appspot.com',
    iosClientId: '769071272569-l712oqbup15vaia0j4qkcavvk6m5il6o.apps.googleusercontent.com',
    iosBundleId: 'com.example.appConectBiblioteca',
  );
}
